# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cplx2real_cov_cpp <- function(var, rho) {
    .Call(`_cplxrv_cplx2real_cov_cpp`, var, rho)
}

dmvn_cpp <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_cplxrv_dmvn_cpp`, x, mean, sigma, logd)
}

eta_to_rho_cpp <- function(eta, a) {
    .Call(`_cplxrv_eta_to_rho_cpp`, eta, a)
}

get_tune_cpp <- function(tune, keep, iter, step, exp_term, target) {
    .Call(`_cplxrv_get_tune_cpp`, tune, keep, iter, step, exp_term, target)
}

inv_cpp <- function(m1) {
    .Call(`_cplxrv_inv_cpp`, m1)
}

invtau2j_bl_cpp <- function(beta, j, sig2, lambda2) {
    .Call(`_cplxrv_invtau2j_bl_cpp`, beta, j, sig2, lambda2)
}

keep_elem <- function(x, to_remove) {
    .Call(`_cplxrv_keep_elem`, x, to_remove)
}

beta_bl_cpp <- function(XtX, XtY, sig2, invtau2) {
    .Call(`_cplxrv_beta_bl_cpp`, XtX, XtY, sig2, invtau2)
}

lam2_bl_cpp <- function(invtau2, p, r, delta) {
    .Call(`_cplxrv_lam2_bl_cpp`, invtau2, p, r, delta)
}

invtau2_bl_cpp <- function(beta, sig2, lam2) {
    .Call(`_cplxrv_invtau2_bl_cpp`, beta, sig2, lam2)
}

sig2_bl_cpp <- function(YtY, XtY, XtX, beta, invtau2, n, p, asig, bsig) {
    .Call(`_cplxrv_sig2_bl_cpp`, YtY, XtY, XtX, beta, invtau2, n, p, asig, bsig)
}

mcmc_bl_cpp <- function(n_mcmc, warm, thin, beta, tau2, lam2, sig2, y, X, r, delta, a_sig, b_sig, draws) {
    .Call(`_cplxrv_mcmc_bl_cpp`, n_mcmc, warm, thin, beta, tau2, lam2, sig2, y, X, r, delta, a_sig, b_sig, draws)
}

mvrnormArma1 <- function(mu, sigma) {
    .Call(`_cplxrv_mvrnormArma1`, mu, sigma)
}

mvrnormArma_inv <- function(mu, sigma_inv) {
    .Call(`_cplxrv_mvrnormArma_inv`, mu, sigma_inv)
}

beta_cbl_cpp <- function(y, X, beta, Sigj_inv_lst, Vinv, sig2, p, all_ind, select_idx_lst, Xj_lst) {
    .Call(`_cplxrv_beta_cbl_cpp`, y, X, beta, Sigj_inv_lst, Vinv, sig2, p, all_ind, select_idx_lst, Xj_lst)
}

ga_cbl_cpp <- function(lam2, sig2, btb, p) {
    .Call(`_cplxrv_ga_cbl_cpp`, lam2, sig2, btb, p)
}

sig2_cbl_cpp <- function(asig, bsig, n, p, y, mu, tau2, btb, Vinv) {
    .Call(`_cplxrv_sig2_cbl_cpp`, asig, bsig, n, p, y, mu, tau2, btb, Vinv)
}

lam2_cbl_cpp <- function(tau2, r, delta, p) {
    .Call(`_cplxrv_lam2_cbl_cpp`, tau2, r, delta, p)
}

mh_log_re_cpp <- function(eta_re, rho_im, mut, ymat, sig2I) {
    .Call(`_cplxrv_mh_log_re_cpp`, eta_re, rho_im, mut, ymat, sig2I)
}

mh_log_im_cpp <- function(rho_re, eta_im, mut, ymat, sig2I) {
    .Call(`_cplxrv_mh_log_im_cpp`, rho_re, eta_im, mut, ymat, sig2I)
}

mcmc_cbl_cpp <- function(n_mcmc, warm, thin, beta, tau2, lam2, sig2, y, X, rho_b, rho_ep, r, delta, a_sig, b_sig, learn_rho, n_chains, keep_re, keep_im, tune_re, tune_im, tune_len, adapt, adapt_step, target_accept_rate, draws) {
    .Call(`_cplxrv_mcmc_cbl_cpp`, n_mcmc, warm, thin, beta, tau2, lam2, sig2, y, X, rho_b, rho_ep, r, delta, a_sig, b_sig, learn_rho, n_chains, keep_re, keep_im, tune_re, tune_im, tune_len, adapt, adapt_step, target_accept_rate, draws)
}

beta_cgdp_cpp <- function(y, X, beta, Sigj_inv_lst, Vinv, sig2, p, all_ind, select_idx_lst, Xj_lst) {
    .Call(`_cplxrv_beta_cgdp_cpp`, y, X, beta, Sigj_inv_lst, Vinv, sig2, p, all_ind, select_idx_lst, Xj_lst)
}

ga_cgdp_cpp <- function(lam, sig2, btb, p) {
    .Call(`_cplxrv_ga_cgdp_cpp`, lam, sig2, btb, p)
}

sig2_cgdp_cpp <- function(asig, bsig, n, p, y, mu, tau2, btb, Vinv) {
    .Call(`_cplxrv_sig2_cgdp_cpp`, asig, bsig, n, p, y, mu, tau2, btb, Vinv)
}

lam_cgdp_cpp <- function(btb, alpha, eta, sig2, p) {
    .Call(`_cplxrv_lam_cgdp_cpp`, btb, alpha, eta, sig2, p)
}

mh_log_ratio_re_cpp_gdp <- function(eta_re, eta_re_star, rho_im, mu, yr, sig2, n, I) {
    .Call(`_cplxrv_mh_log_ratio_re_cpp_gdp`, eta_re, eta_re_star, rho_im, mu, yr, sig2, n, I)
}

mh_log_ratio_im_cpp_gdp <- function(rho_re, eta_im, eta_im_star, mu, yr, sig2, n, I) {
    .Call(`_cplxrv_mh_log_ratio_im_cpp_gdp`, rho_re, eta_im, eta_im_star, mu, yr, sig2, n, I)
}

a_cond_log_cgdp_cpp <- function(a, p, btb, sig2, eta) {
    .Call(`_cplxrv_a_cond_log_cgdp_cpp`, a, p, btb, sig2, eta)
}

e_cond_log_cgdp_cpp <- function(e, p, btb, sig2, alpha) {
    .Call(`_cplxrv_e_cond_log_cgdp_cpp`, e, p, btb, sig2, alpha)
}

mcmc_cgdp_cpp <- function(n_mcmc, warm, thin, beta, tau2, lam, sig2, y, X, rho_b, rho_ep, alpha, eta, a_sig, b_sig, learn_rho, griddy, n_chains, keep_re, keep_im, tune_re, tune_im, tune_len, adapt, adapt_step, target_accept_rate, draws) {
    .Call(`_cplxrv_mcmc_cgdp_cpp`, n_mcmc, warm, thin, beta, tau2, lam, sig2, y, X, rho_b, rho_ep, alpha, eta, a_sig, b_sig, learn_rho, griddy, n_chains, keep_re, keep_im, tune_re, tune_im, tune_len, adapt, adapt_step, target_accept_rate, draws)
}

beta_ct_cpp <- function(XtVinvy, Siginv, sig2) {
    .Call(`_cplxrv_beta_ct_cpp`, XtVinvy, Siginv, sig2)
}

tau2_ct_cpp <- function(beta, rho_b, df, p, sig2) {
    .Call(`_cplxrv_tau2_ct_cpp`, beta, rho_b, df, p, sig2)
}

sig2_ct_cpp <- function(asig, bsig, n, p, y, beta, X, Vinv, Vbinv) {
    .Call(`_cplxrv_sig2_ct_cpp`, asig, bsig, n, p, y, beta, X, Vinv, Vbinv)
}

mcmc_ct_cpp <- function(n_mcmc, warm, thin, beta, tau2, sig2, y, X, rho_b, rho_ep, df, a_sig, b_sig, learn_rho, n_chains, keep_re, keep_im, tune_re, tune_im, tune_len, adapt, adapt_step, target_accept_rate, draws) {
    .Call(`_cplxrv_mcmc_ct_cpp`, n_mcmc, warm, thin, beta, tau2, sig2, y, X, rho_b, rho_ep, df, a_sig, b_sig, learn_rho, n_chains, keep_re, keep_im, tune_re, tune_im, tune_len, adapt, adapt_step, target_accept_rate, draws)
}

beta_gdp_cpp <- function(XtX, XtY, sig2, invtau) {
    .Call(`_cplxrv_beta_gdp_cpp`, XtX, XtY, sig2, invtau)
}

invtau_gdp_cpp <- function(beta, sig2, lam) {
    .Call(`_cplxrv_invtau_gdp_cpp`, beta, sig2, lam)
}

sig2_gdp_cpp <- function(YtY, XtY, XtX, beta, invtau, n, p, asig, bsig) {
    .Call(`_cplxrv_sig2_gdp_cpp`, YtY, XtY, XtX, beta, invtau, n, p, asig, bsig)
}

lamj_gdp_cpp <- function(betaj, sig2, alpha, eta) {
    .Call(`_cplxrv_lamj_gdp_cpp`, betaj, sig2, alpha, eta)
}

a_cond_log_cpp <- function(a, p, beta, sig2, eta) {
    .Call(`_cplxrv_a_cond_log_cpp`, a, p, beta, sig2, eta)
}

e_cond_log_cpp <- function(e, p, beta, sig2, alpha) {
    .Call(`_cplxrv_e_cond_log_cpp`, e, p, beta, sig2, alpha)
}

mcmc_gdp_cpp <- function(n_mcmc, warm, thin, beta, invtau, lam, sig2, y, X, a_sig, b_sig, alpha, eta, griddy, draws) {
    .Call(`_cplxrv_mcmc_gdp_cpp`, n_mcmc, warm, thin, beta, invtau, lam, sig2, y, X, a_sig, b_sig, alpha, eta, griddy, draws)
}

beta_t_cpp <- function(XtX, XtY, sig2, tau2) {
    .Call(`_cplxrv_beta_t_cpp`, XtX, XtY, sig2, tau2)
}

tau2_t_cpp <- function(beta, atau, btau, sig2, p) {
    .Call(`_cplxrv_tau2_t_cpp`, beta, atau, btau, sig2, p)
}

sig2_t_cpp <- function(YtY, XtY, XtX, beta, tau2, n, p, asig, bsig) {
    .Call(`_cplxrv_sig2_t_cpp`, YtY, XtY, XtX, beta, tau2, n, p, asig, bsig)
}

mcmc_t_cpp <- function(n_mcmc, warm, thin, beta, tau2, sig2, y, X, a_tau, b_tau, a_sig, b_sig, draws) {
    .Call(`_cplxrv_mcmc_t_cpp`, n_mcmc, warm, thin, beta, tau2, sig2, y, X, a_tau, b_tau, a_sig, b_sig, draws)
}

mh_log_ratio_im_cpp <- function(rho_re, eta_im, eta_im_star, mut, ymat, sig2I) {
    .Call(`_cplxrv_mh_log_ratio_im_cpp`, rho_re, eta_im, eta_im_star, mut, ymat, sig2I)
}

mh_log_ratio_re_cpp <- function(eta_re, eta_re_star, rho_im, mut, ymat, sig2I) {
    .Call(`_cplxrv_mh_log_ratio_re_cpp`, eta_re, eta_re_star, rho_im, mut, ymat, sig2I)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_cplxrv_mvrnormArma`, n, mu, sigma)
}

rcnorm_cpp <- function(n, mu, var, rho, is_real = TRUE, is_circular = FALSE) {
    .Call(`_cplxrv_rcnorm_cpp`, n, mu, var, rho, is_real, is_circular)
}

rcpp_hello_world <- function() {
    .Call(`_cplxrv_rcpp_hello_world`)
}

rcpparma_hello_world <- function() {
    .Call(`_cplxrv_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_cplxrv_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_cplxrv_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_cplxrv_rcpparma_bothproducts`, x)
}

rho_to_eta_cpp <- function(rho, a) {
    .Call(`_cplxrv_rho_to_eta_cpp`, rho, a)
}

rrinvgauss <- function(n, mu, lambda) {
    .Call(`_cplxrv_rrinvgauss`, n, mu, lambda)
}

rrinvgauss_vec <- function(n, mu, lambda) {
    .Call(`_cplxrv_rrinvgauss_vec`, n, mu, lambda)
}

sample_vec <- function(x, size, replace, prob) {
    .Call(`_cplxrv_sample_vec`, x, size, replace, prob)
}

